Integrate tauri-upload-plugin
nchapman/pulsar pull request #27
Opened 2024-02-27 08:47 UTC by ospfranco

Adds an API callable from JS that allows to download/upload files

closes #3

2024-02-27 08:49 UTC, ospfranco commented on src/main.tsx
> +import { database } from '../db.tsx';
I think this changed slipped. Let me know so I can revert it.

2024-02-27 08:49 UTC, ospfranco commented on src-tauri/Cargo.toml
> -tauri = { version = "1.5", features = [ "shell-sidecar"] }
I guess only I will be doing Rust for the time being. So this is just automatic linting done by VSCode and the rust linter.

2024-02-27 20:49 UTC, demetrxx requested changes
LGTM! 
Just 1 minor change

2024-02-27 20:49 UTC, demetrxx commented on src/main.tsx
> +import { database } from '../db.tsx';
Yeah, I believe this one is extra

2024-02-29 00:10 UTC, nchapman approved these changes
LGTM 👍

2024-02-29 13:38 UTC, merged

2024-02-29 13:39 UTC, ospfranco commented
Merged