Integrate nebula into the project
nchapman/pulsar pull request #95
Opened 2024-04-03 15:54 UTC by Warefoxe

Integrate nebula into the project using cargo git reference. 
Create nebula plugin with javascript API

2024-04-04 07:17 UTC, ospfranco commented on src-tauri/tauri-plugin-nebula/src/lib.rs
> +async fn init_model<R: Runtime>(
Maybe some documentation on this functions would be useful?

2024-04-04 07:17 UTC, ospfranco commented on src-tauri/tauri-plugin-nebula/src/lib.rs
> +pub enum Error {
is it worth it to put on it's own file? will it be re-used as the plugin grows?

2024-04-04 07:17 UTC, ospfranco commented on src-tauri/tauri-plugin-nebula/src/lib.rs
> +    if let Some(mm) = state.models.lock().await.get_mut(&model) {
noob question, where do the models stream responses back to JS? don't quite understand what each function does but I'm not seeing any event emit.

2024-04-04 07:17 UTC, ospfranco commented on src/widgets/chat/api/chatApi.ts
> +invoke('plugin:nebula|init');
This can throw and is also async right?

2024-04-04 07:17 UTC, ospfranco commented on src/widgets/chat/model/chat.ts
> +import { combine, createEffect, createEvent, createStore, sample } from 'effector';
@demetrxx can you review changes on the frontend?

2024-04-04 12:49 UTC, Warefoxe commented on src-tauri/tauri-plugin-nebula/src/lib.rs
> +pub enum Error {
Yes, I will made it

2024-04-04 12:50 UTC, Warefoxe commented on src-tauri/tauri-plugin-nebula/src/lib.rs
> +    if let Some(mm) = state.models.lock().await.get_mut(&model) {
I suppose not use events, just call predict function and get predicted text, but if needed stream I will try to implement it

2024-04-04 12:52 UTC, Warefoxe commented on src/widgets/chat/api/chatApi.ts
> +invoke('plugin:nebula|init');
yes, will update this

2024-04-05 06:43 UTC, ospfranco commented
@Warefoxe can you merge the tip of `develop` into this branch? It will run CI to make sure everything builds on all platforms.

2024-04-05 15:39 UTC, Warefoxe commented
@ospfranco , I am change integration code, now it try to simulate stream with events, please check updated code.

2024-04-08 06:20 UTC, ospfranco commented
Tests would also be good. Even if there is no model to use, you can just mock the responses, but make sure that the correct events are emitted and so.

2024-04-08 06:30 UTC, ospfranco commented on src-tauri/tauri-plugin-nebula/src/lib.rs
> +async fn init_model<R: Runtime>(
Docs are still missing

2024-04-09 12:21 UTC, ospfranco commented on src/entities/model/index.ts
>  export { downloadModel } from './api/downloadModel.ts';
Barrel files are not good, they will degrade performance once the app is large enough. I would strongly discourage their use.

https://marvinh.dev/blog/speeding-up-javascript-ecosystem-part-7/

2024-04-10 06:43 UTC, demetrxx requested changes

2024-04-10 06:43 UTC, demetrxx commented on src/entities/model/lib/modelExists.ts
> +  const entries = await readDir(MODELS_DIR_NAME, { dir: BaseDirectory.AppLocalData });
According to Nick's comment, we need to change .AppLocalData to .appData

2024-04-10 06:43 UTC, demetrxx commented on src/widgets/chat/api/chatApi.ts
> -}
1. How do you distinguish between user and assistant messages then?
2. Why don't you cut last message, it's an empty assistant message for UI purposes only

2024-04-10 06:43 UTC, demetrxx commented on src/entities/model/api/downloadModel.ts
> +  await createDir(MODELS_DIR_NAME, { dir: BaseDirectory.AppLocalData, recursive: true });
change to .appData

2024-04-10 06:43 UTC, demetrxx commented on src/entities/model/lib/getModelPath.ts
>    const localDir = await appLocalDataDir();
change to appDataDir()

2024-04-10 10:53 UTC, ospfranco commented on src/widgets/chat/api/chatApi.ts
> -}
1. I don't know how this is supposed to work. I assume one should fetch the entire conversation into the model, it doesn't really care? @Warefoxe 
2. I will take a look into this

2024-04-10 12:49 UTC, Warefoxe commented on src/widgets/chat/api/chatApi.ts
> -}
I have add parameter to context initialisation with set of messages

2024-04-11 05:48 UTC, ospfranco commented
Tests are still missing but if @demetrxx says everything is ok, I will take care of them on a separate PR please.

2024-04-11 09:53 UTC, demetrxx approved these changes
Looks good to me!

2024-04-12 07:56 UTC, merged